language: c
os: linux
dist: trusty
compiler: gcc
sudo: require
install:
  - ./tests/ci/install.sh
script:
  - ./tests/ci/run.sh
env:
  global:
    - secure: "1qAHFxnz0gIxMMl9DAVzoPvVSpOacWT2G6ItcaoaVe1r4OANzpoHBlbyHX2I/1KFe+BohzjS9kXA4NrlPaL81qfvu9E6qZ9yai/+0gHdzZttB2uvdyFXyDVye3CHHDlYMfRRQf6C+eYs5CKeedWq9Q3arO1GyAWiL9RcW1466sg="
    - COVERITY_SCAN_BRANCH_PATTERN=coverity_scan
    - COVERITY_SCAN_NOTIFICATION_EMAIL="bernat@luffy.cx"
    - RUN_COVERITY=0
  matrix:
    - LLDPD_CONFIG_ARGS=""
    - LLDPD_CONFIG_ARGS="--with-embedded-libevent"
    - LLDPD_CONFIG_ARGS="--disable-privsep --with-snmp"
    - LLDPD_CONFIG_ARGS="--with-snmp --with-xml --with-json --disable-lldpmed --disable-dot1 --disable-dot3 --disable-custom"
    - LLDPD_CONFIG_ARGS="--enable-oldies"
matrix:
  include:
    - os: linux
      compiler: clang
      env: LLDPD_CONFIG_ARGS="--with-snmp --with-xml --with-json"
    - os: osx
      compiler: clang
      env: LLDPD_CONFIG_ARGS="--with-snmp --with-xml --with-json"
    - os: linux
      compiler: gcc
      env:
        - RUN_COVERITY=1
        - LLDPD_CONFIG_ARGS="--with-snmp --with-xml --with-json"
