language: c
os: linux
compiler:
  - clang
  - gcc
install:
  - ./.travis/install.sh
script:
  - ./.travis/run.sh
env:
  - LLDPD_CONFIG_ARGS=""
  - LLDPD_CONFIG_ARGS="--with-embedded-libevent"
  - LLDPD_CONFIG_ARGS="--disable-privsep --with-snmp"
  - LLDPD_CONFIG_ARGS="--with-snmp --with-xml --with-json --disable-lldpmed --disable-dot1 --disable-dot3"
matrix:
  include:
    - os: osx
      compiler: clang
      env: LLDPD_CONFIG_ARGS="--with-embedded-libevent"
    - os: osx
      compiler: clang
      env: LLDPD_CONFIG_ARGS="--with-snmp --with-xml --with-json"
