language: c
group: deprecated-2017Q3
os: linux
dist: trusty
compiler: gcc
sudo: require
install:
  - ./tests/ci/install.sh
script:
  - ./tests/ci/run.sh
env:
  matrix:
    - LLDPD_CONFIG_ARGS=""
    - LLDPD_CONFIG_ARGS="--with-embedded-libevent"
    - LLDPD_CONFIG_ARGS="--disable-shared --enable-static"
    - LLDPD_CONFIG_ARGS="--disable-privsep --with-snmp"
    - LLDPD_CONFIG_ARGS="--with-snmp --disable-lldpmed --disable-dot1 --disable-dot3 --disable-custom"
    - LLDPD_CONFIG_ARGS="--enable-oldies"
    - LLDPD_CONFIG_ARGS="--with-seccomp"
matrix:
  include:
    - os: linux
      compiler: clang
      env: LLDPD_CONFIG_ARGS="--with-snmp --with-xml"
    - os: osx
      compiler: clang
      env: LLDPD_CONFIG_ARGS="--with-snmp --with-xml"
    - os: osx
      compiler: clang
      env: 
        - MAKE_ARGS=""
        - LLDPD_CONFIG_ARGS="--with-embedded-libevent"
    - os: osx
      compiler: clang
      if: tag =~ ^[0-9]
      env:
        - MAKE_ARGS=""
        - LLDPD_UPLOAD=1
        - LLDPD_CONFIG_ARGS="--prefix=/usr/local --localstatedir=/var --sysconfdir=/private/etc --with-embedded-libevent --without-snmp --without-xml"
deploy:
  - provider: s3
    skip_cleanup: true
    local_dir: upload
    bucket: lldpd-releases
    acl: public_read
    on:
      all_branches: true
      condition: "$LLDPD_UPLOAD = 1"
