name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: 0 7 1 * *
jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        config-args:
          - "--with-embedded-libevent"
          - "--disable-shared --enable-static"
          - "--disable-privsep --with-snmp"
          - "--with-snmp --disable-lldpmed --disable-dot1 --disable-dot3 --disable-custom"
          - "--enable-oldies"
          - "--enable-dtrace"
          - "--with-seccomp"
        compiler:
          - gcc
        release:
          - false
        include:
          - os: ubuntu-latest
            config-args: ''
            release: true
          - os: ubuntu-latest
            compiler: clang
            config-args: "--with-snmp --with-xml"
          - os: macos-latest
            compiler: clang
            config-args: "--with-snmp --with-xml"
          - os: macos-latest
            compiler: clang
            config-args: >
              --prefix=/usr/local
              --localstatedir=/var
              --sysconfdir=/private/etc
              --with-embedded-libevent
              --without-snmp
              --without-xml
            release: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install stuff
        run: ./tests/ci/install.sh
      - name: Build and run tests
        run: ./tests/ci/run.sh
        env:
          LLDPD_CONFIG_ARGS: ${{ matrix.config-args }}
          CC: ${{ matrix.compiler }}
      - name: Upload release tarball
        uses: actions/upload-artifact@v2
        if: matrix.release && matrix.os == 'ubuntu-latest'
        with:
          name: tarball
          path: lldpd-*.tar.gz
          if-no-files-found: error
      - name: Upload MacOS release package
        uses: actions/upload-artifact@v2
        if: matrix.release && matrix.os == 'macos-latest'
        with:
          name: package
          path: lldpd-*.pkg
          if-no-files-found: error
  docker:
    needs: build
    runs-on: ubuntu-latest
    name: Build Docker images
    if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: |
            ghcr.io/lldpd/lldpd
          tags: |
            type=schedule,pattern=master
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
            linux/ppc64el
            linux/i386
            linux/arm/v7
            linux/arm/v6
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
